# Generated by Django 4.0.6 on 2022-10-31 12:28

from django.db import migrations


def track_new_good_deal_settings(apps, schema_editor):
    try:
        from common.klaviyo.util import track_good_deal_settings
        User = apps.get_model('account.CustomUser')
        for user in User.objects.all():
            track_good_deal_settings(user_id=user.id)
    except Exception as exc:
        print('Migration account.0027 failed:', exc)
        print('But probably there is nothing to worry about')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_emailsettings_favorites_match_notification_and_more'),
    ]

    operations = [
        migrations.RunPython(track_new_good_deal_settings)
    ]
